### ISSUE TITLE
[Task] explorer 분석 및 화면 개발

### ISSUE THREAD

**Issue by verecahill** [codestates/BTAFinalProject-05#7]
### ISSUE
- Detail : explorer 필요한 기능 분석
- 프론트엔드 구조 초안
- devnet 데이터 조회 및 추가 필요 데이터 확인

### TODO
1. [x] explorer 필요한 기능 분석
2. [x] 프론트엔드 구조 초안
3. [x] devnet 데이터 조회 및 추가 필요 데이터 확인
